name: salsa

channels:
  - conda-forge

#NOTE: gcc compiler is needed to install some packages
# This environment contains the minimum dependencies for running SALSA.
dependencies:
    - astropy
    - h5py
    - matplotlib
    - numpy
    - pip
    - scipy
    - yt
    - pip:
        - mpi4py
        - trident
