name: salsa-env

channels:
  - conda-forge

#NOTE: gcc compiler is needed to install some packages
dependencies:
    - astropy
    - h5py
    - matplotlib
    - numpy
    - pip
    - pooch
    - pytest
    - scipy
    - sphinx
    - sphinx_automodapi
    - sphinx_rtd_theme
    - yt
    - pip:
        - mpi4py
        - trident
