#!/bin/bash -login
#PBS -l walltime=4:00:00,nodes=32:ppn=8
#PBS -l mem=256gb
#PBS -j oe
#PBS -N total_mass_box

### load necessary modules, e.g.
### module load HDF5

### change to the working directory where your code is located
cd /mnt/research/galaxies-REU/bbrzycki/scripts

### call your executable

mpirun -np 256 python total_mass_box.py

###env | grep PBS  

qstat -f ${PBS_JOBID}     # Print out final statistics about resource uses before job exits
