#!/bin/bash -login
#PBS -l walltime=3:30:00,nodes=32:ppn=8
#PBS -l mem=256gb
#PBS -j oe
#PBS -N total_o_mass_low

cd /mnt/scratch/f0002318/lowres_analysis

mpirun -np 256 python total_mass_box_save.py '/mnt/scratch/dsilvia/simulations/reu_sims/MW_1638kpcBox_800pcCGM_200pcDisk_lowres/DD????/DD????' 'O V' 'a' 64

mpirun -np 256 python total_mass_box_save.py '/mnt/scratch/dsilvia/simulations/reu_sims/MW_1638kpcBox_800pcCGM_200pcDisk_lowres/DD????/DD????' 'O IV' 'a' 64

###env | grep PBS  

qstat -f ${PBS_JOBID}     # Print out final statistics about resource uses before job exits
