name: salsa
channels:
  - conda-forge
dependencies:
  - astropy
  - h5py
  - matplotlib
  - mpi4py  # auto install OpenMPI
  - numpy
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - yt
  - pip
  - pip:
    - trident
    - sphinx_automodapi

